project:
  type: website
  output-dir: docs

website:
  title: "issmaldonado-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Data_Wrangle.qmd
      

format:
  html:
    theme: lux
    backgroundcolor: "#D3D3D3"
    css: styles.css
    toc: true



